name: Close Issue Message
on:
  workflow_dispatch:
  issues:
    types: [closed]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write
    steps:
      - uses: aws-actions/closed-issue-message@refactoragain
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            This issue is now closed. Comments on closed issues are hard for our team to see. 
            If you need more assistance, please open a new issue that references this one.-
