name: Test

on:
  workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4 
            - name: Test
              uses: ./test-local-action
              with:
                  num1: 1
