name: Test sync

on:
    workflow_dispatch:

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Git
              run: |
                git config user.name "GitHub Actions"
                git config user.email "tom@github.com"
                git push https://${{ secrets.TOMTOKEN }}@github.com/awslabs/aws-github-test testbranch