name: Test sync

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Git
              run: |
                git config user.name "GitHub Actions"
                git config user.email "tom@github.com"
                git remote set-url origin https://${{ secrets.TOMTOKEN }}@github.com/awslabs/aws-github-test.git
                git config --unset-all http.https://github.com/.extraheader
            - name: Push
              run: |
                git push origin HEAD:testbranch